"""Word v2 structured factors.

These are factors present in the Word v2 document but absent from the
executable system. They are backed by returned Wind parquet tables under
`资料/word_only_factor_data_direct_only_processed/parquet`.
"""
from __future__ import annotations

from factor_lib.registry import register_external


_DEFS = [
    (
        "PEPCTL", "公司内生信息", "估值", -1, "PE历史分位",
        "word_v2", "PEPCTL", "derived",
        "PE在个股自身近36个月有效月末序列中的中位秩分位；仅使用正PE，分位越低，估值越便宜。",
        "PEPCTL = [count(PE_i < PE_t) + (count(PE_i = PE_t) + 1) / 2] / N，i为含当月在内的近36个月正PE月末观测。",
        "AShareValuationIndicator.S_VAL_PE_TTM",
        False,
    ),
    (
        "FWDPE", "公司内生信息", "估值", -1, "Forward PE",
        "word_v2", "FWDPE", "level",
        "未来 12 个月一致预期口径的滚动 PE；仅保留正 PE，数值越低，预期估值越便宜。",
        "FWDPE = AShareConsensusRollingData.EST_PE，ROLLING_TYPE='FTTM'，EST_PE>0。",
        "AShareConsensusRollingData.EST_PE; ROLLING_TYPE; TRADE_DT",
        True,
    ),
    (
        "EV2EBIT", "公司内生信息", "估值", -1, "总市值/EBIT",
        "word_v2", "EV2EBIT", "derived",
        "总市值 / TTM EBIT；历史代码沿用EV2EBIT，当前口径不等同于企业价值EV/EBIT。EBIT 为正时有效，数值越低越便宜。",
        "总市值/EBIT = AShareValuationIndicator.S_VAL_EV / PITFinancialFactor.S_DFA_EBIT_TTM；当前回传字段S_VAL_EV按总市值口径提供，EBIT<=0置缺失。",
        "AShareValuationIndicator.S_VAL_EV; PITFinancialFactor.S_DFA_EBIT_TTM",
        True,
    ),
    (
        "ROEVOL", "公司内生信息", "盈利质量", -1, "ROE波动率",
        "word_v2", "ROEVOL", "derived",
        "ROE_TTM 近 12 个月度截面的滚动标准差；越低表示盈利能力越稳定。",
        "ROEVOL = std(S_DFA_ROE_TTM, 12)，按个股月末序列滚动计算，至少 3 期。",
        "PITFinancialFactor.S_DFA_ROE_TTM",
        False,
    ),
    (
        "RATINGCHG", "投资者行为信息", "分析师预期", 1, "评级变化",
        "word_v2", "RATINGCHG", "asof_latest",
        "月末取Wind 90日周期最新可见评级上调家数减下调家数；快照水平不跨日累加，超过90日无新快照则为空。",
        "RATINGCHG = latest(S_WRATING_UPGRADE - S_WRATING_DOWNGRADE, S_WRATING_CYCLE=263002000, 0<=age<90日)。",
        "AShareStockRatingConsus.S_WRATING_UPGRADE; AShareStockRatingConsus.S_WRATING_DOWNGRADE; S_WRATING_CYCLE; RATING_DT",
        False,
    ),
    (
        "SURVEYCNT", "投资者行为信息", "关注度", 1, "机构调研次数",
        "word_v2", "SURVEYCNT", "window_count",
        "近 60 日按 EVENT_ID 去重的机构调研活动次数；关注度越高越好。",
        "SURVEYCNT = count_distinct(AshareISActivity.EVENT_ID, 近60日)。",
        "AshareISActivity.S_SURVEYDATE; AshareISActivity.EVENT_ID",
        False,
    ),
    (
        "SURVEYINSTCNT", "投资者行为信息", "关注度", 1, "调研机构数量",
        "word_v2", "SURVEYINSTCNT", "window_count_distinct",
        "近 60 日参与调研的去重机构数量；覆盖机构越多越好。",
        "SURVEYINSTCNT = count_distinct(AShareISParticipant.S_INSTITUTIONCODE, 近60日调研事件)。",
        "AshareISActivity.EVENT_ID; AShareISParticipant.S_INSTITUTIONCODE",
        False,
    ),
    (
        "ORCAGR3Y", "公司内生信息", "成长", 1, "营业收入3年复合增速",
        "word_v2", "ORCAGR3Y", "derived",
        "TTM 营业收入相对 36 个月前的年化复合增速；增速越高越好。",
        "ORCAGR3Y = (S_DFA_OR_TTM / lag36(S_DFA_OR_TTM))^(1/3)-1；当前值和滞后值均需为正。",
        "PITFinancialFactor.S_DFA_OR_TTM",
        False,
    ),
    (
        "CAPEXGROWTH", "公司内生信息", "成长", 1, "CAPEX增速",
        "word_v2", "CAPEXGROWTH", "derived",
        "购建固定资产、无形资产和其他长期资产支付现金 TTM 相对上年同期增速；资本开支扩张越强，成长投入越高。",
        "CAPEXGROWTH = CAPEX_TTM / lag_same_quarter(CAPEX_TTM, 1年) - 1；CAPEX优先取正CASH_PAY_ACQ_CONST_FIOLTA，0/缺失时回退至正STOT_CASH_OUTFLOWS_INV_ACT。",
        "AShareCashFlow.CASH_PAY_ACQ_CONST_FIOLTA; STOT_CASH_OUTFLOWS_INV_ACT; ANN_DT; REPORT_PERIOD",
        False,
    ),
    (
        "RDEXPRATIOCHG", "公司内生信息", "成长", 1, "△研发费用占比",
        "word_v2", "RDEXPRATIOCHG", "derived",
        "研发费用 TTM 占营业收入 TTM 比例相对上年同期的变化；数值越高，研发投入意愿边际越强。",
        "RDEXPRATIOCHG = RD_EXPENSE_TTM / OPER_REV_TTM - lag_same_quarter(RD_EXPENSE_TTM / OPER_REV_TTM, 1年)。",
        "AShareANNFinancialIndicator.RD_EXPENSE; AShareIncome.TOT_OPER_REV; OPER_REV; ANN_DT; REPORT_PERIOD",
        False,
    ),
    (
        "INTDEBTRATIO", "公司内生信息", "财务质量", -1, "有息负债占负债比",
        "word_v2", "INTDEBTRATIO", "asof_latest",
        "公告可得口径下的核心有息负债占负债总额比例；比例越低越稳健。",
        "INTDEBTRATIO = (ST_BORROW + NON_CUR_LIAB_DUE_WITHIN_1Y + LT_BORROW + BONDS_PAYABLE + LEASE_LIAB + INT_PAYABLE) / S_DFA_TOTLIAB。",
        "AShareBalanceSheet.ST_BORROW; NON_CUR_LIAB_DUE_WITHIN_1Y; LT_BORROW; BONDS_PAYABLE; LEASE_LIAB; INT_PAYABLE; PITFinancialFactor.S_DFA_TOTLIAB; ANN_DT",
        False,
    ),
    (
        "GOODWILLRATIO", "公司内生信息", "财务质量", -1, "商誉占比",
        "word_v2", "GOODWILLRATIO", "asof_latest",
        "公告可得口径下的商誉占总资产比例；比例越高，潜在减值风险越高。",
        "GOODWILLRATIO = GOODWILL / TOT_ASSETS，GOODWILL缺失按0处理，TOT_ASSETS<=0时置缺失；取月末前最新公告财报。",
        "AShareBalanceSheet.GOODWILL; AShareBalanceSheet.TOT_ASSETS; ANN_DT",
        False,
    ),
    (
        "ARRATIO", "公司内生信息", "财务质量", -1, "应收账款占收入比例",
        "word_v2", "ARRATIO", "derived",
        "公告可得应收票据及应收账款合计占 TTM 营业收入比例；比例越低，收入质量越好。",
        "ARRATIO = (ACCT_RCV + NOTES_RCV) / S_DFA_OR_TTM；两个应收分项都缺失时置缺失，仅其中一项缺失时将该分项按0合并；资产负债表取月末前最新公告，收入使用同月 PITFinancialFactor。",
        "AShareBalanceSheet.ACCT_RCV; AShareBalanceSheet.NOTES_RCV; PITFinancialFactor.S_DFA_OR_TTM; ANN_DT",
        False,
    ),
    (
        "DIVPAYOUT", "公司内生信息", "分红回报", 1, "分红率",
        "word_v2", "DIVPAYOUT", "derived",
        "最新年度现金分红总额占月末可得净利润 TTM 的比例；比例越高，利润分配意愿越强。",
        "DIVPAYOUT = latest(年度现金分红总额) / S_DFA_NETPROFIT_TTM；分红总额优先取正TOT_CASH_DVD，0/缺失时依次回退至正OTHER_TOT_CASH_DVD、正CASH_DVD_PER_SH_PRE_TAX×TOT_SHR；净利润<=0置缺失。",
        "AShareDividend.TOT_CASH_DVD; OTHER_TOT_CASH_DVD; CASH_DVD_PER_SH_PRE_TAX; TOT_SHR; PITFinancialFactor.S_DFA_NETPROFIT_TTM",
        False,
    ),
    (
        "DIVSTREAK", "公司内生信息", "分红回报", 1, "连续分红年数",
        "word_v2", "DIVSTREAK", "derived",
        "截至月末最新年度的连续现金分红年数；连续性越强越好。",
        "DIVSTREAK = 连续年度现金分红总额>0 的年数，按公告可得日 as-of 取最新；分红总额按TOT_CASH_DVD、OTHER_TOT_CASH_DVD、CASH_DVD_PER_SH_PRE_TAX×TOT_SHR的正值顺序回退。",
        "AShareDividend.TOT_CASH_DVD; OTHER_TOT_CASH_DVD; CASH_DVD_PER_SH_PRE_TAX; TOT_SHR; REPORT_PERIOD; ANN_DT",
        False,
    ),
    (
        "DIVGROWTH", "公司内生信息", "分红回报", 1, "分红增长率",
        "word_v2", "DIVGROWTH", "derived",
        "最新年度现金分红总额相对上一年度的增长率；增长越高，分红回报改善越强。",
        "DIVGROWTH = 年度现金分红总额 / 上一年度现金分红总额 - 1；分红总额按TOT_CASH_DVD、OTHER_TOT_CASH_DVD、CASH_DVD_PER_SH_PRE_TAX×TOT_SHR的正值顺序回退；上一年度<=0置缺失。",
        "AShareDividend.TOT_CASH_DVD; OTHER_TOT_CASH_DVD; CASH_DVD_PER_SH_PRE_TAX; TOT_SHR; REPORT_PERIOD; ANN_DT",
        False,
    ),
    (
        "SUSPENDDAYS", "市场交易信息", "交易状态", -1, "停牌天数",
        "word_v2", "SUSPENDDAYS", "rolling_count",
        "近 60 个交易日样本中的停牌天数；停牌越多流动性越差。",
        "SUSPENDDAYS = count(S_DQ_TRADESTATUS='停牌' or S_DQ_AMOUNT<=0, 近60个交易日)。",
        "AShareEODPrices.S_DQ_TRADESTATUS; AShareEODPrices.S_DQ_AMOUNT; TRADE_DT",
        False,
    ),
    (
        "LIMITUPDAYS", "市场交易信息", "交易状态", 1, "涨停天数",
        "word_v2", "LIMITUPDAYS", "rolling_count",
        "近 60 个交易日涨停天数；作为短期强势/事件热度信号。",
        "LIMITUPDAYS = count(UP_DOWN_LIMIT_STATUS=1, 近60个交易日)。",
        "AShareEODPrices.UP_DOWN_LIMIT_STATUS; TRADE_DT",
        False,
    ),
    (
        "LIMITDOWNDAYS", "市场交易信息", "交易状态", -1, "跌停天数",
        "word_v2", "LIMITDOWNDAYS", "rolling_count",
        "近 60 个交易日跌停天数；跌停越多风险越高。",
        "LIMITDOWNDAYS = count(UP_DOWN_LIMIT_STATUS=-1, 近60个交易日)。",
        "AShareEODPrices.UP_DOWN_LIMIT_STATUS; TRADE_DT",
        False,
    ),
    (
        "ONEBOARDDAYS", "市场交易信息", "交易状态", -1, "一字板天数",
        "word_v2", "ONEBOARDDAYS", "rolling_count",
        "近 60 个交易日一字涨跌停天数；一字板越多，可交易性越差。",
        "ONEBOARDDAYS = count(OPEN=HIGH=LOW=CLOSE 且 UP_DOWN_LIMIT_STATUS in (1,-1), 近60个交易日)。",
        "AShareEODPrices.S_DQ_OPEN; S_DQ_HIGH; S_DQ_LOW; S_DQ_CLOSE; UP_DOWN_LIMIT_STATUS",
        False,
    ),
    (
        "MARGINBALCHG", "投资者行为信息", "融资融券", 1, "融资余额变化",
        "word_v2", "MARGINBALCHG", "mom_diff",
        "融资余额月度变化；余额上升代表杠杆资金净流入。",
        "MARGINBALCHG = S_MARGIN_TRADINGBALANCE - lag1(S_MARGIN_TRADINGBALANCE)，按个股月末序列计算。",
        "AShareMarginTrade.S_MARGIN_TRADINGBALANCE; TRADE_DT",
        False,
    ),
    (
        "MARGINBUYRATIO", "投资者行为信息", "融资融券", 1, "融资买入占比",
        "word_v2", "MARGINBUYRATIO", "window_ratio",
        "近 60 日融资买入额占成交额比例；比例越高代表杠杆买入更活跃。",
        "MARGINBUYRATIO = sum(S_MARGIN_PURCHWITHBORROWMONEY[元], 近60日) / (sum(S_DQ_AMOUNT[千元], 近60日) × 1000)。",
        "AShareMarginTrade.S_MARGIN_PURCHWITHBORROWMONEY; AShareEODPrices.S_DQ_AMOUNT; TRADE_DT",
        False,
    ),
    (
        "HOLDERAVGCHG", "投资者行为信息", "筹码结构", 1, "人均持股变化",
        "word_v2", "HOLDERAVGCHG", "mom_pct",
        "流通股本/股东户数的月度变化率；人均持股上升代表筹码趋于集中。",
        "HOLDERAVGCHG = (FREE_SHARES_TODAY / latest(S_HOLDER_NUM)) / lag1(...) - 1。",
        "AShareHolderNumber.S_HOLDER_NUM; AShareEODPrices.FREE_SHARES_TODAY",
        False,
    ),
    (
        "INSTHOLD", "投资者行为信息", "筹码结构", 1, "机构持仓比例",
        "word_v2", "INSTHOLD", "asof_latest",
        "最新报告期机构持股比例合计；机构持仓比例越高，专业投资者认可度越高。",
        "INSTHOLD = clip(sum(S_HOLDER_PCT), 0, 100)，按股票、报告期汇总机构持仓，汇总后截断至[0,100]，月末取最新公告报告期。",
        "AShareinstHolderDerData.S_HOLDER_PCT; REPORT_PERIOD; ANN_DATE",
        False,
    ),
    (
        "TOP10HOLD", "投资者行为信息", "筹码结构", 1, "持仓集中度",
        "word_v2", "TOP10HOLD", "asof_latest",
        "最新报告期前十大股东持股比例合计；比例越高代表筹码越集中。",
        "TOP10HOLD = clip(sum(S_HOLDER_PCT), 0, 100)，按股票、公告日和报告期汇总前十大股东，汇总后截断至[0,100]，月末取最新公告报告期。",
        "AShareInsideHolder.S_HOLDER_PCT; REPORT_PERIOD; ANN_DT",
        False,
    ),
    (
        "UNLOCKPRESS", "投资者行为信息", "筹码结构", -1, "解禁压力",
        "word_v2", "UNLOCKPRESS", "future_window_sum",
        "月末已知、未来 90 日限售股解禁比例合计；潜在供给压力越高越不利。",
        "UNLOCKPRESS优先使用月度PIT字段UNLOCK_RATIO_90D；缺少月度PIT表时，按ANN_DT不晚于月末筛选事件，并对未来90日S_SHARE_RATIO求和。",
        "unlock_monthly_pit_90d.UNLOCK_RATIO_90D; AShareFreeFloatCalendar.ANN_DT; S_INFO_LISTDATE; S_SHARE_RATIO",
        False,
    ),
    (
        "ANALYSTCOVER", "投资者行为信息", "分析师预期", 1, "近20日评级机构覆盖数",
        "word_v2", "ANALYSTCOVER", "asof_latest",
        "月末前20个交易日内最新评级机构覆盖数；窗口内无观测则为空。",
        "ANALYSTCOVER = latest(S_WRATING_INSTNUM, 过去20个交易日)。",
        "AShareStockRatingConsus.S_WRATING_INSTNUM; RATING_DT",
        False,
    ),
    (
        "ESTEARNREV", "投资者行为信息", "分析师预期", 1, "盈利预测调整幅度",
        "word_v2", "ESTEARNREV", "level",
        "未来 12 个月一致预测净利润近 1 个月调整幅度；上修越多越好。",
        "ESTEARNREV = ConsensusExpectationFactor.S_WEST_NETPROFIT_FTM_1M。",
        "ConsensusExpectationFactor.S_WEST_NETPROFIT_FTM_1M; TRADE_DT",
        False,
    ),
    (
        "TARGETPRICECHG", "投资者行为信息", "分析师预期", 1, "目标价调整幅度",
        "word_v2", "TARGETPRICECHG", "mom_pct",
        "月末前最新目标价相对上月变化率；上调越多越好。",
        "TARGETPRICECHG = latest(S_EST_PRICE) / lag1(latest(S_EST_PRICE)) - 1。",
        "AShareStockRatingConsus.S_EST_PRICE; RATING_DT",
        False,
    ),
    (
        "BUYBACKRATIO", "事件驱动信息", "回购增减持", 1, "回购金额占流通市值比",
        "word_v2", "BUYBACKRATIO", "window_sum",
        "近365日各回购事件最新已公告金额合计占月末流通市值比例；比例越高，回购支持越强。",
        "BUYBACKRATIO = sum(每个EVENT_ID月末前最新正AMT, 近365日公告) / (月末S_DQ_MV × 10000)，0≤value≤5；AMT为元，S_DQ_MV为万元。",
        "AshareStockRepo.EVENT_ID; AMT; ANN_DT; AShareEODDerivativeIndicator.S_DQ_MV",
        False,
    ),
    (
        "PLACEDISCOUNT", "事件驱动信息", "融资并购", -1, "定增折价率",
        "word_v2", "PLACEDISCOUNT", "window_mean",
        "近365日各定增事件最新可见折价率均值；折价越高，对老股东摊薄和价格压力越大。",
        "PLACEDISCOUNT = mean(每个EVENT_ID月末前最新S_FELLOW_DISCNTRATIO, 近365日公告)。",
        "ASharePlacement.EVENT_ID; S_FELLOW_DISCNTRATIO; ANN_DT",
        False,
    ),
    (
        "PLACEMENTSIZE", "事件驱动信息", "资本运作", 1, "定增规模",
        "word_v2", "PLACEMENTSIZE", "window_ratio",
        "近 365 日定增募集资金占月末总市值比例；作为资本运作事件强度信号。",
        "PLACEMENTSIZE = sum(每个EVENT_ID截至月末近365日内按ANN_DT可见的最新正募集金额) / S_VAL_MV_ARD；募集金额优先正S_FELLOW_COLLECTION，0/缺失时回退至正EXP_COLLECTION。",
        "ASharePlacement.EVENT_ID; ANN_DT; S_FELLOW_COLLECTION; EXP_COLLECTION; AShareValuationIndicator.S_VAL_MV_ARD",
        False,
    ),
    (
        "MERGERSIZE", "事件驱动信息", "资本运作", 1, "并购规模",
        "word_v2", "MERGERSIZE", "window_ratio",
        "近365日仅统计收购方的人民币并购交易对价占月末总市值比例；并购规模越大，资本运作强度越高。",
        "MERGERSIZE = sum(event_amount × 10000, 近365日，CRNCY_CODE='CNY'，PARTY_ROLE_CODE='325001000') / S_VAL_MV_ARD，0≤value≤20；同一股票、EVENT_ID在窗口内只取最新有效记录，事件日=coalesce(UPDATE_DATE, ANN_DATE)，event_amount优先取正TRADE_VALUE，否则取正CASH_PAYMENT。",
        "MergerEvent.EVENT_ID; TRADE_VALUE; CASH_PAYMENT; CRNCY_CODE; UPDATE_DATE; ANN_DATE; MergerParticipant.S_INFO_WINDCODE; PARTY_ROLE_CODE; AShareValuationIndicator.S_VAL_MV_ARD",
        False,
    ),
    (
        "INCENTIVESIZE", "事件驱动信息", "股权激励", 1, "激励规模",
        "word_v2", "INCENTIVESIZE", "window_sum",
        "近 365 日公告股权激励数量占比合计；同一计划下不同激励序列保留分项，完全重复行不重复加总。",
        "INCENTIVESIZE = sum(每个EQINC_PLAN_EVENT_ID、S_INC_SEQUENCE截至月末近365日内最新可见INC_NUMBERS_RATE)。",
        "AShareEquityIncentive.EQINC_PLAN_EVENT_ID; S_INC_SEQUENCE; INC_NUMBERS_RATE; ANN_DT",
        False,
    ),
    (
        "RISKINVESTCNT", "事件驱动信息", "风险事件", -1, "被立案",
        "word_v2", "RISKINVESTCNT", "window_count",
        "近 60 日被立案调查事件数；事件越多风险越高。",
        "RISKINVESTCNT = count(RiskInvestigation, 近60日公告)。",
        "AShareRiskInvestigation.STR_ANNDATE",
        False,
    ),
    (
        "PUNISHAMT", "事件驱动信息", "风险事件", -1, "处罚公告金额",
        "word_v2", "PUNISHAMT", "window_sum",
        "近 365 日违规处罚金额合计；全字段完全相同的源行只计一次。",
        "PUNISHAMT = sum(AMOUNT, 近365日公告，全字段精确去重)。",
        "AShareIllegalEvent.AMOUNT; ANN_DT",
        False,
    ),
    (
        "LAWSUITAMT", "事件驱动信息", "风险事件", -1, "重大诉讼金额",
        "word_v2", "LAWSUITAMT", "window_sum",
        "近 365 日诉讼涉案/判决绝对金额合计；全字段完全相同的源行只计一次。",
        "LAWSUITAMT = sum(优先正RESULTAMOUNT，0/缺失时回退至正AMOUNT, 近365日公告，全字段精确去重)。",
        "AShareLawsuit.RESULTAMOUNT; AShareLawsuit.AMOUNT; ANN_DT",
        False,
    ),
    (
        "AUDITQUAL", "公司内生信息", "财务质量", -1, "审计意见",
        "word_v2", "AUDITQUAL", "asof_latest",
        "月末前最新审计意见风险等级；标准无保留为 0，非标意见风险等级更高。",
        "AUDITQUAL = map(S_STMNOTE_AUDIT_CATEGORY: 405001000->0, 405002000->1, 405003000->2, 405004000/405005000->3)。",
        "AShareAuditOpinion.S_STMNOTE_AUDIT_CATEGORY; ANN_DT",
        False,
    ),
    (
        "MAJORHOLDERCHG", "事件驱动信息", "股东行为", 1, "大股东增持/减持",
        "word_v2", "MAJORHOLDERCHG", "window_ratio",
        "近 365 日重要股东增减持金额占月末总市值比例；增持为正、减持为负。",
        "MAJORHOLDERCHG = sum(sign(TRANSACT_TYPE) * TRANSACT_QUANTITY * AVG_PRICE, 近365日) / S_VAL_MV_ARD。",
        "AShareMjrHolderTrade.HOLDER_TYPE; TRANSACT_TYPE; TRANSACT_QUANTITY; AVG_PRICE; AShareValuationIndicator.S_VAL_MV_ARD",
        False,
    ),
    (
        "EXECHOLDERCHG", "事件驱动信息", "股东行为", 1, "高管增持/减持",
        "word_v2", "EXECHOLDERCHG", "window_ratio",
        "近 365 日董监高增减持金额占月末总市值比例；增持为正、减持为负。",
        "EXECHOLDERCHG = sum(sign(TRANSACT_TYPE) * TRANSACT_QUANTITY * AVG_PRICE, 近365日，HOLDER_TYPE=3) / S_VAL_MV_ARD。",
        "AShareMjrHolderTrade.HOLDER_TYPE; TRANSACT_TYPE; TRANSACT_QUANTITY; AVG_PRICE; AShareValuationIndicator.S_VAL_MV_ARD",
        False,
    ),
    (
        "FINRESTATEMENT", "事件驱动信息", "风险事件", -1, "财务重述",
        "word_v2", "FINRESTATEMENT", "window_count",
        "近 365 日前期会计差错更正或追溯调整事件数；事件越多，财务报告稳定性越弱。",
        "FINRESTATEMENT = count(S_CHANGE_ITEMCODE in 前期差错/追溯调整, 近365日公告)。",
        "AShareAccountingChange.S_CHANGE_ITEMCODE; ANN_DATE; CompanySecurityMap.S_INFO_WINDCODE",
        False,
    ),
    (
        "PROFITNOTICEBEAT", "事件驱动信息", "业绩事件", 1, "预告超预期",
        "word_v2", "PROFITNOTICEBEAT", "event_surprise",
        "业绩预告净利润中值相对披露前最新一致预测净利润的超预期幅度；超预期越高越好。",
        "PROFITNOTICEBEAT = 业绩预告净利润中值 / latest(FY1一致预测净利润，缺失时用FTTM) - 1。",
        "AShareProfitNotice.S_PROFITNOTICE_NETPROFITMIN/MAX; AShareConsensusRollingData.NET_PROFIT",
        False,
    ),
    (
        "REPORTSURPRISE", "事件驱动信息", "业绩事件", 1, "财报超/低预期",
        "word_v2", "REPORTSURPRISE", "event_surprise",
        "财报实际归母净利润相对披露前最新一致预测净利润的偏离；越高表示越超预期。",
        "REPORTSURPRISE = 年报NET_PROFIT_EXCL_MIN_INT_INC / latest(FY1一致预测净利润，缺失时用FTTM) - 1。",
        "AShareIncome.NET_PROFIT_EXCL_MIN_INT_INC; AShareConsensusRollingData.NET_PROFIT",
        False,
    ),
    (
        "UNLOCKMVRATIO", "事件驱动信息", "供给冲击", -1, "解禁市值/流通市值",
        "word_v2", "UNLOCKMVRATIO", "future_window_ratio",
        "月末已知、未来 90 日解禁股份占当前自由流通股比例；比例越高，供给冲击越大。",
        "UNLOCKMVRATIO = sum(S_SHARE_LST × 10,000, 未来90日) / (FREE_SHARES_TODAY × 10,000)，且ANN_DT不晚于月末。",
        "AShareFreeFloatCalendar.ANN_DT; S_INFO_LISTDATE; S_SHARE_LST; S_SHARE_LST_IS_ANN; AShareEODPrices.FREE_SHARES_TODAY",
        False,
    ),
    (
        "REFINPRESS", "事件驱动信息", "供给冲击", -1, "再融资压力",
        "word_v2", "REFINPRESS", "window_ratio",
        "近 365 日定增和配股募集资金占月末总市值比例；再融资规模越大，潜在供给压力越高。",
        "REFINPRESS = (sum(定增募集资金)+sum(配股募集资金), 近365日) / S_VAL_MV_ARD；定增按股票、EVENT_ID取截至月末最新正金额，配股无事件ID时去除股票、ANN_DT、金额完全相同的重复行；已募集字段为0/缺失时回退至对应正预计募集字段。",
        "ASharePlacement.EVENT_ID; ANN_DT; S_FELLOW_COLLECTION; EXP_COLLECTION; AShareRightIssue.ANN_DT; S_RIGHTSISSUE_NETCOLLECTION; S_EXPECTED_FUND_RAISING; AShareValuationIndicator.S_VAL_MV_ARD",
        False,
    ),
]


for code, l1, l2, direction, name_cn, sfile, sfield, transform, desc, formula, wind, positive_only in _DEFS:
    register_external(
        code=code,
        l1=l1,
        l2=l2,
        direction=direction,
        name_cn=name_cn,
        source_file=sfile,
        source_field=sfield,
        description=desc,
        formula=formula,
        wind_source=wind,
        positive_only=positive_only,
        transform=transform,
    )
